### ISSUE TITLE
Sparse option not working as documented

### ISSUE THREAD

**Issue by e-e-e** [datproject/dat-node#105]
Setting sparse to try in options does not stop the dat from being completely downloaded.
I am setting the options like this:
```js
const opts = {
  key: 'a key',
  sparse: true,
};

Dat(dir, opts, cb);
```
It looks like the options are not being passed to hyperdrive.

**Comment by joehand** [comment]
Yes, I need to add a test for this! I'm not sure I've tried sparse downloads so this may be broken =(.

Can you make sure you have fresh node_modules? The latest version of hypercore fixed an issue with the sparse archives (where it'd download everything even if it was sparse).

**Comment by joehand** [comment]
Got a failing test case. Thanks for reporting this, I'm on it.

**Comment by joehand** [comment]
Opened a PR in hyperdrive to fix this: https://github.com/mafintosh/hyperdrive/pull/128

**Comment by e-e-e** [comment]
Thanks so much for your prompt fix @joehand. You are amazing!

**Comment by joehand** [comment]
@e-e-e should be fixed if you upgrade hyperdrive!

**Comment by e-e-e** [comment]
@joehand thanks so much for this. I will try it out asap.
