### ISSUE TITLE
SLEEP - hyperdrive v8 

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#126]
🚗 💨 

Starting to update dat-node for v8! Going to add track what dependencies need updating, missing/deprecated API changes to make, etc. 

## Dependency Update Needs:

- [x] ~hyperdrive-import-files ([branch](https://github.com/juliangruber/hyperdrive-import-files/tree/hyperdrive-v8)) ([PR](https://github.com/juliangruber/hyperdrive-import-files/pull/53))~ (PR ready, but using mirror-folder instead)
- [ ] hyperdrive-stats (@juliangruber)
- [x] hyperdrive-network-speed ([branch](https://github.com/joehand/hyperdrive-network-speed/tree/sleep)) ([PR](https://github.com/joehand/hyperdrive-network-speed/pull/4) - published)
- [x] hyperdrive-duplicate ([branch](https://github.com/joehand/hyperdrive-duplicate/tree/sleep)) ([PR](https://github.com/joehand/hyperdrive-duplicate/pull/1) - published)

#### hyperdrive-stats

* remove leveldb dependency
* Use updated APIs to get stats
* change archive.open to on('ready')

## Dat-Node

[SLEEP branch](https://github.com/datproject/dat-node/tree/sleep)

**Comment by joehand** [comment]
Pushed a big new update today. I have *most* of the importing, storage, and network updates done. There are some minor updates we need to look at for importing but they are more optional. I think I have a good handle on that.

## Where I need help:

### Stats: 

#### `filesTotal` & `bytesTotal` (for latest version)

I have a very basic [stats API](https://github.com/datproject/dat-node/blob/sleep/lib/stats.js#L10-L16) but this doesn't take into account history. So a file added + updated will count twice.

The only way I see to do this is either reading over the history (as we were doing before) or a recursive readdir/stat loop to get the latest stats. We could use [count-files](https://github.com/joehand/count-files) to do the readdir/stat but seems like this may be slow for big archives (I can test it on my 1.5tb archive tomorrow). Anyone have better ideas?

#### `bytesProgress` & download tracking

Some way to get existing download and track download progress.

#### Peer Info

I had implemented a new api to get more accurate peer information ([see these lines](https://github.com/datproject/dat-node/blob/sleep/lib/stats.js#L20-L42)). It looks like at least some of that hypercore api is still there (`remoteLength`) but we need to think about how/if to reimplement this.

---
Checkout the full & updated TODO list in [the PR](https://github.com/datproject/dat-node/pull/128)

**Comment by karissa** [comment]
Regarding stats, I think it's ok for this release to just do what we were doing before in reading over the history. We can optimize it if we find it to be too slow.

Regarding peer info, what's wrong with the count that hypercore gives? I'd try to keep it simply if possible -- it'd be cool if hypercore was good at handling and updating its own peer count accurately.

**Comment by juliangruber** [comment]
I'm working on getting the current stats/indexing approach working with hyperdrive, then we can see if we can go without indexing too

**Comment by mafintosh** [comment]
@joehand @juliangruber i'm releasing stuff for the bytestotal/progress tracking sometime this week prob. there is a new tiny index being added for quickly downloading latest files only and i can use this index to cache these things as well

**Comment by joehand** [comment]
Merged Sleep to master, gonna release soon. 

*Stats: I have a basic stats api that we should be able to use without breaking when hyperdrive-stats or hypercore is updated with more stats stuff.
* Download tracking sounds like its coming soon in hypercore|drive.
* Peer info: hypercore supported the basic API I was using before, we can extend as needed.

I'm going to close this issue and we can take stock of missing parts and open individual issues as they come up building into desktop/cli.
