### ISSUE TITLE
uncaught permission error

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-node#144]
when sharing a folder you don't have write access to, this uncatchable error is thrown:

```bash
 ∴  iZotope : dat create
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/julian/Documents/iZotope/.dat/metadata.bitfield'
```

I'm looking into the right place to fix this.

**Comment by juliangruber** [comment]
fixed in https://github.com/mafintosh/hyperdrive/pull/161

**Comment by joehand** [comment]
Fixed in hyperdrive.
