### ISSUE TITLE
question: private dats?

### ISSUE THREAD

**Issue by dominictarr** [datproject/dat-node#162]
I'm not seeing anything about it in the docs, but I remember @mafintosh told me that dats were encrypted (or could be made private) so that only peers that I had explicitly shared a dat link with would be able to decrypt my dat. Is this correct?

**Comment by e-e-e** [comment]
My understanding is that Dat's are private by default. They use discover keys for finding peers so even the swarm does not know your public key. Only those who you share it with directly.

**Comment by karissa** [comment]
Yep that's right. They aren't encrypted on disk, however, just in transit. Read more here: https://docs.datproject.org/faq#security-and-privacy

**Comment by dominictarr** [comment]
thanks
