### ISSUE TITLE
Import changes to existing files?

### ISSUE THREAD

**Issue by jayrbolton** [datproject/dat-node#168]
This is probably a newb question, but I'm trying to do this with two users (without using {watch:true}):
- userA creates a dat and imports files (join the network, imports files, never closes the dat)
- userB downloads the dat from userA (joins the network, closes it when done)
- userA modifies one of the existing files (what can I call here? just importFiles?)
- userB tries to download changes (joins the network again, downloads, does not get changes)

I'm thinking this might have a simple answer, but if not I could put up a code example. I'm using `dat.archive.on('sync')` to see when the userB's downloads are done. And I'm just using importFiles with the callback. Also playing with some import stats progress, but it doesnt work on a file change (https://github.com/jayrbolton/dat-pki/blob/master/lib/utils/importAll.js)

**Comment by joehand** [comment]
> userB tries to download changes (joins the network again, downloads, does not get changes)

Sounds like its connecting and emitting `sync` before the metadata is updated (this may be a hypercore/drive issue or just a weird API). Do you *know* it is downloading something?

You may try waiting for an update or checking if its modified. For example:

```js
dat.joinNetwork(function () {
  dat.archive.metadata.update(function () {
    dat.archive.on('sync', exit)
  })
})
```

You may also be able to use the stats to check if the version has updated when `sync` fires.

The hyperdrive API is not great for this and I'd like to have something to expose this better in the dat-node API. But seeing how people are using it will be really helpful =).

Check our [download code](https://github.com/datproject/dat/blob/master/src/lib/download.js) in the CLI for more implementation bits.

**Comment by jayrbolton** [comment]
Thanks very much for the clues, I'll play with the examples today

**Comment by jayrbolton** [comment]
I played with it in a separate repo using a forked process: https://github.com/jayrbolton/dat-file-import-test

It worked as soon as I added the `dat.archive.metadata.update` callback wrapper as you suggested. I dont have it quite working in dat-pki, but there's probably something else going on

**Comment by jayrbolton** [comment]
Okay I found my issue, it was just related to me getting all the various layers of dats in dat-pki all mixed up in my head and importing on the wrong dat. :man_shrugging:
