### ISSUE TITLE
What is utp?

### ISSUE THREAD

**Issue by styfle** [datproject/dat-node#170]
The readme mentions an option for utp that says

> use utp in discovery swarm

What is utp? Is this supposed to say UDP?

**Comment by joehand** [comment]
> uTP is a TCP-like implementation of LEDBAT documented as a BitTorrent extension in BEP-29. uTP provides provides reliable, ordered delivery while maintaining minimum extra delay. It is implemented on top of UDP to be cross-platform and functional today. As a result, uTP is the primary transport for uTorrent peer-to-peer connections.

UTP is uses UDP =)

The module dependency is https://github.com/mafintosh/utp-native which uses https://github.com/bittorrent/libutp (where the above snippet is from).

**Comment by styfle** [comment]
Thanks!

Should this link appear in the docs somewhere so someone (like me) can click to read more?

**Comment by joehand** [comment]
Yes, opened issue in docs. Thanks.
