### ISSUE TITLE
dat.close does not close the db

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-node#18]
When trying to add tests to #17, we realized `dat.close()` does not also run `dat.db.close()` - this seemed like a bit of a gotcha, and reckon it might be worth resolving. Thanks!

**Comment by juliangruber** [comment]
imo it shouldn't close the db, since it also doesn't explicitly open it

**Comment by yoshuawuyts** [comment]
@juliangruber do you mean if a database has been passed in externally? Yeah that sounds like a problem indeed. I think a branch in behavior might resolve that:
- when a user runs `dat.open()`, `dat.close()` should close `dat`
- when a user passes in a database explicitely, e.g. `dat.open(leveldb())`, `dat.close()` should not touch the db instance

I feel this would create consistency in the behavior and granularity of managing `dat` instances. Either you know what you're doing and are responsible for the database instance, or the database is an implementation detail. In that case it might also make sense to have the recommended API be `db.close()` rather than `dat.db.close()` for further consistency.

Not sure about this all though; very new to all this, and just floating ideas out there :sparkles:

**Comment by joehand** [comment]
In theory this sounds good. But along with the database opening/closing we have to think about how to treat closed archives. It's not possible to [re-open a closed archive](https://github.com/mafintosh/hyperdrive/blob/master/archive.js#L472). So we'd have to make a new archive. I'm not sure if this is a technical limitation or a design choice.

**Comment by juliangruber** [comment]
imo this goes to show that the api is a bit to flexible, then the db should always be passed in, to be more explicit.

**Comment by joehand** [comment]
I think this is handled better in the 1.0.0 API. 

If you pass `opts.db` then it expects you to close it. Otherwise, it closes the database on `dat.close()`.

There is no open function so you cannot re-open the same instance.
