### ISSUE TITLE
dat segfaults if stopping and restarting on the same dat instance

### ISSUE THREAD

**Issue by yoshuawuyts** [datproject/dat-node#19]
### Expected behavior

Dat should warn me if I try and use the same dat instance after closing it. Or even better: it should allow me to start, stop and restart without problem.
### Actual behavior

Dat segfaults
### Steps to reproduce behavior

``` js
const dat = Dat({dir: fixtures})

dat.open(function () {
  dat.share(function (err) {
    dat.close(function () {
      dat.db.close(secondRun)
    })
  })
})

function secondRun () {
  dat.open(function () {
    dat.share(function (err) {
      // SEGFAULT!
    })
  })
}
```

**Comment by juliangruber** [comment]
i've seen this too in tests! thought it would be a nodejs / osx problem though

**Comment by juliangruber** [comment]
the errors I was seeing looked like event loop errors

**Comment by yoshuawuyts** [comment]
it was suggested on IRC this might be a leveldb cleanup issue; working on https://github.com/joehand/dat-js/issues/18 yielded this error again; it certainly seems like it might be a possibility

**Comment by joehand** [comment]
I've mostly hit this error when working with tests and trying to close the database (or running tests on travis). I did some debugging before but didn't get any deeper understanding then: *sometimes when I close the database I get a segfault*.

**Comment by joehand** [comment]
I'm getting a segfault regularly on tests for the [remove-webrtc branch](https://github.com/datproject/dat-js/compare/remove-webrtc) now.

**Comment by karissa** [comment]
its when you close the db then try to open it again, right?

**Comment by joehand** [comment]
We should fix this bug by doing:

> Dat should warn me if I try and use the same dat instance after closing it. 

And:

> Dat should warn me if I try to close a dat instance that is already closed.
