### ISSUE TITLE
Data redundancy

### ISSUE THREAD

**Issue by ragjunk** [datproject/dat-node#191]
Is there a way to setup dat-nodes such that there is N copy of the files on different nodes for redundancy purposes? With this, a given "key" may be served by more than one node, so there is resiliency. Is there a way this can be achieved?

**Comment by joehand** [comment]
Yes, each key can be shared across many nodes but only one process can write the files. For example, with the `dat` CLI (which uses dat-node). You can do:

Computer 1:
```
dat share
<prints key>
```

Computer 2:
```
dat clone <key>
```

And the data will be on both computers.

**Comment by joehand** [comment]
Also see https://github.com/joehand/dat-download for some tips on how to download via dat-node.

**Comment by ragjunk** [comment]
Thanks for the quick response! So, looks like the *writing* node cannot go offline in this case. We have a use case where there are N nodes (say 8), of which a subset (say, 3) of them serve as data stores for all. Ideally, all the N nodes should be able to *write* to *any* of the 3  data nodes and they all will be synchronized automatically. Reading from any of the 3 data nodes is not a problem. This way, a single node doesn't become the bottleneck for a given key. We can certainly build this on top of dat-node, but wondering if there is a native way to do this with Dat.

**Comment by joehand** [comment]
Yes, that makes sense. Being able to write from multiple computers is in the roadmap.

Development is happening in github.com/mafintosh/hyperdb (which will be used inside of hyperdrive). And specification is a WIP at https://github.com/datprotocol/DEPs/pull/10.

If you'd like it sooner, you can also check out https://github.com/poga/hyperdrive-ln and https://github.com/substack/hyperdrive-multiwriter. Both are built on the older version of hyperdrive but may give tips for implementation.

**Comment by ragjunk** [comment]
Thanks for the pointers. Really appreciate your time!
