### ISSUE TITLE
Feature Request: DEP-0006 Session Data Support in NodeJS

### ISSUE THREAD

**Issue by D1plo1d** [datproject/dat-node#225]
I am reporting:

- [ ] a bug or unexpected behavior
- [ ] general feedback
- [x] feature request
- [ ] security issue 

Beaker supports Dep-0006 as a method for broadcasting data between peers. This is useful for peer discovery if both peers are using Beaker. In trying to control a farm of 3D printers from Beaker I have stumbled upon a use case where one peer is using Beaker (the client) and connected to a dat single page app and the other peers are running dat-node (in my case: each 3D printer is a dat-node peer running on a raspberry pi).

How could I send and receive session data from dat-node to a Beaker peer?

https://www.datprotocol.com/deps/0006-session-data-extension/
https://beakerbrowser.com/docs/apis/experimental-datpeers

**Comment by D1plo1d** [comment]
@RangerMauve That's awesome, thanks for putting this together. It sounds like the beaker to node-dat peers that you have working already may be enough for what I'm trying to do. And if not I'll make sure to share anything I manage to figure out. Cheers!

**Comment by okdistribute** [comment]
You can create session data with hypercore-protocol extensions. This is accessible through the dat-sdk or with hypercore-protocol directly. See github.com/cabal-club/cabal-core/ for an example of this.
