### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by TS22082** [datproject/dat-node#227]
I am reporting:

- [x] a bug or unexpected behavior
- [ ] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* windows:
* Node Version: 10.14.2
* dat-node Version: 13.11.4

### Expected behavior

Files to be available to share over the dat network via the key printed in the console.
```
rl.question('Specify path for dat creation: ', (path) => {
  Dat(path, function (err, dat) {
    if (err) throw err
    dat.importFiles()
    dat.joinNetwork()
    console.log('My Dat link is: dat://', dat.key.toString('hex'))
    console.log(`Initiated DAT in file location: ${path}`);
  })
  rl.close();
});
```

### Actual behavior

a dat address is generated followed by an error message

### Debug Logs

```
$ node app.js
Specify path for dat creation: /
My Dat link is: dat:// 42f081a90cec46476f4ade2812fe6f22216f3fa34524c1d7c13e7cc3621f7557
Initiated DAT in file location: /
C:\Users\ts220\Documents\CODE\bionet-middleware\node_modules\dat-node\lib\import-files.js:41
      if (err) return cb(err)
                      ^

TypeError: cb is not a function
    at EventEmitter.<anonymous> (C:\Users\ts220\Documents\CODE\bionet-middleware\node_modules\dat-node\lib\import-files.js:41:23)
    at EventEmitter.emit (events.js:182:13)
    at C:\Users\ts220\Documents\CODE\bionet-middleware\node_modules\mirror-folder\index.js:131:32
    at FSReqWrap.oncomplete (fs.js:154:21)

```

**Comment by ralphtheninja** [comment]
`cb` is required in `.importFiles()`

https://github.com/datproject/dat-node/blob/ab6c935e4fe7b56d2bbe5848c3c10e972a3f2a88/dat.js#L174-L176

Maybe dat should throw a more descriptive error though. Or pass a no-op callback, but you usually don't do this for async methods.

**Comment by TS22082** [comment]
I was trying to follow the instructions from the docs. What is the cb? Is this any callback? 

Docs say: 'cb - called when import is finished.' 
`var importer = dat.importFiles([src], [opts], [cb])`

Side thought- is this happening because I've already ran the app and its causing a clash? The code was basically lifted from the first example.

from docs first example basically the same:
```
var Dat = require('dat-node')

// 1. My files are in /joe/cat-pic-analysis
Dat('/joe/cat-pic-analysis', function (err, dat) {
  if (err) throw err
  // 2. Import the files
  dat.importFiles()
  // 3. Share the files on the network!
  dat.joinNetwork()
  // (And share the link)
  console.log('My Dat link is: dat://', dat.key.toString('hex'))
})
```
Thanks for the reply and your help! It's really appreciated.

**Comment by ralphtheninja** [comment]
> from docs first example basically the same:

Aah ok, I didn't see it was an example from the README, sorry. Maybe this example is outdated and should be updated.

You could try doing `dat.importFiles(function () {})`

**Comment by joehand** [comment]
> Side thought- is this happening because I've already ran the app and its causing a clash? The code was basically lifted from the first example.

Yes! I think this is what is happening. It is getting an error and then trying to call `cb(err)`. So we should fix this! 

That line should either throw an error or emit an error on the `progress` event emitter if there is not a callback (I think throwing would make more sense here).

**Comment by TS22082** [comment]
Awesome. Is there a way I can check if there is a dat folder already set up? I'm thinking about using the fs module and checking the filesystem, does the dat-node module have another way?
