### ISSUE TITLE
100% cpu when syncing a single file on my local machine

### ISSUE THREAD

**Issue by jedahan** [datproject/dat-node#233]
I can easily get dat-cli (and my own applications using dat-node) to peg the cpu to 100% and eventually not receive updates.

I am reporting:
- [x] a bug or unexpected behavior

node v11.7.0, dat 13.11.5

Steps to reproduce:
```bash
mkdir -p test/{local,remote}
cd test/local
edit test.txt
# in a second terminal
cd test/local
dat share
# in a third terminal
cd test/remote
dat clone dat://<output of dat share from second terminal>
cd <output of dat share from second terminal>
dat sync
# in a fourth terminal
watch -n1 cat test/remote/<output of dat share from second terminal>/test.txt
# now make lots of edits to test.txt (like 1 a second for about 30 seconds)
```

The first few updates are snappy, but soon each update will peg the node process to 100%, and will take longer and longer to sync, and eventually stop syncing (or take over 10 minutes so I cannot tell if they eventually sync).

Video https://vimeo.com/324228171

**Comment by joehand** [comment]
Thanks, I've been able to reproduce and start identifying where the bug is coming from. It appears something in the `hyperdrive._trackLatest` is unnecessarily looping. This code hasn't been changed for two years and I'm *pretty sure* this bug hasn't been out there this entire time. 

I've created a basic test case for @mafintosh here: https://gist.github.com/joehand/ad9d3a3dc7f7d7ab611307d396025fbe.

**Comment by jedahan** [comment]
Interesting enough, when I switched to v10 and changed `'syncing'` to `'update'`, things look okay:

```
dest syncing
  dest version: 290
  source version: 290
dest syncing
  dest version: 291
  source version: 291
dest syncing
  dest version: 292
  source version: 292
dest syncing
  dest version: 293
  source version: 293
dest syncing
  dest version: 294
  source version: 294
dest syncing
  dest version: 295
  source version: 295
dest syncing
  dest version: 296
  source version: 296
dest syncing
  dest version: 297
  source version: 297
dest syncing
  dest version: 298
  source version: 298
dest syncing
  dest version: 299
  source version: 299
```

**Comment by karissa** [comment]
So it seems to work as expected with node version 10 (and 8)

**Comment by jedahan** [comment]
sorry, I meant node 11, but the v10 branch of hyperdrive

**Comment by joehand** [comment]
@jedahan the latest release of hyperdrive `9.14.3` may address this issue. Can you see if updating it has fixed that for you?

**Comment by karissa** [comment]
closing, feel free to reopen if the bug persists. Thank you for reporting!

**Comment by jedahan** [comment]
confirmed that test case is fixed, thank you all!
