### ISSUE TITLE
Errors running `example/share.js`

### ISSUE THREAD

**Issue by dmitriz** [datproject/dat-node#239]
I am reporting:

- [x] a bug or unexpected behavior
- [ ] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: Mac OS 10.8.5
* Node Version: v10.15.3
* dat-node Version: dat-node@3.5.15

### Expected behavior

Running `node example/share.js` is expected to end with console message.

### Actual behavior

Errors reported:

```sh
→ node examples/share.js 
dyld: lazy symbol binding failed: Symbol not found: _memset_s
  Referenced from: /Users/dmitrizaitsev/Repos/dat-node/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _memset_s
  Referenced from: /Users/dmitrizaitsev/Repos/dat-node/node_modules/sodium-native/prebuilds/darwin-x64/libsodium.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

```

### Debug Logs

Running `DEBUG=dat* node examples/share.js` produces exactly the same error message.

**Comment by dmitriz** [comment]
Seems to be caused by the main`dat` module:

https://github.com/datproject/dat/issues/1110

**Comment by okdistribute** [comment]
This should be fixed now with dat-node@next while on node 12
