### ISSUE TITLE
Stream Support?

### ISSUE THREAD

**Issue by wenkesj** [datproject/dat-node#46]
Is there be a possibility, in the future (or maybe present), to support Read/Write streams? Does this exist? I ask because it would be **awesome**ly useful with frameworks like RN, or fs-independent platforms

**Comment by mafintosh** [comment]
Streams are already supported if you usentge underlying hyperdrive API. https://github.com/mafintosh/hyperdrive

I can show a couple of examples if you can describe your use case in a bit more detail.
