### ISSUE TITLE
How to deal with archive snapshots?

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#47]
Right now I have to do this thing: https://github.com/datproject/dat-node/blob/1.0/index.js#L59.

**Comment by juliangruber** [comment]
@joehand can you give more context what the issue is here?

**Comment by joehand** [comment]
> @joehand can you give more context what the issue is here?

Yes, sorry I meant to but spaced it =). 

The key for snapshots are key is not available until the end, as we know. This makes it difficult to expose the key on `dat.key`. Common actions expect the key to be available so this will cause errors, especially if `dat.key` is never populated for snapshots.

The workaround I have is okay. I wrapped the importer callback function to set `dat.key`. 

There may be further issues once a snapshot is created & finalized on disk. `archive.owner` is false after you close then reopen a snapshot. Since there is no private key, we may have to treat it differently here and in the CLI.

**Summary**: I mostly have workable implementations for basic snapshot usage. However, it is a bit hacky, will not support all snapshot use cases, and may have some edge case issues.

## Question

Should we support snapshots *at all* in this library?

**Comment by juliangruber** [comment]
> Question
> 
> Should we support snapshots at all in this library?

are there consumers of this in need of snapshots? From a dat-desktop PoV we're not there yet, so it's hard for me to tell api requirements snapshot wise.

**Comment by joehand** [comment]
I think what we are doing is working well. But there is still the issue of: 

> There may be further issues once a snapshot is created & finalized on disk. archive.owner is false after you close then reopen a snapshot. Since there is no private key, we may have to treat it differently here and in the CLI.

to think about. We'll see what issues come up here and revisit before the next milestone.

**Comment by joehand** [comment]
Should be fixed in the https://github.com/datproject/dat-node/pull/65
