### ISSUE TITLE
Update repository NPM and README

### ISSUE THREAD

**Issue by I-n-d-e-r** [datproject/dat-node#49]
Please update repository NPM, after the installation date of the NPM-node using:

`npm install dat-node`

on computer install the old version which contains errors and the index.php file looks completely different than this repository.

Another thing are inconsistencies, for example, on the NPM get the following information in a repository readme.md it is not, a little confusing.

```js
// dat-js OLD API 
var dat = Dat({dir: dir})
dat.share(function () {
   // automatically import files 
   // automatically join network 
  console.log('now sharing:', dat.key.toString())
})
```

In dat-node this would be:

```js
// dat-node v1 NEW API 
Dat(dir, function (err, dat) {
  var network = dat.joinNetwork(opts) // join network 
  console.log('now sharing:', dat.key.toString())
 
  // import files 
  var importer = dat.importFiles(opts, function () {
    console.log('done importing files')
  })
 
  // get stats info (via hyperdrive-stats) 
  var stats = dat.trackStats()
})
```

**Comment by joehand** [comment]
@I-n-d-e-r thanks for reporting the issue! I published the [1.0 branch](https://github.com/datproject/dat-node/tree/1.0) to NPM on accident. 

You can run `npm install dat-node@0.1.2` to get the correct version. Apologies for the confusion.
