### ISSUE TITLE
URL in dat.json should update if key is different

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#51]
Right now we write the URL to dat.json on create. But if dat.json exists already, we [read in the existing](https://github.com/datproject/dat-node/blob/1.0/index.js#L94) URL.

If that URL is a `dat://` url and the keys don't match, we need to update it or bad things will happen.

**Comment by karissa** [comment]
Seems like we're getting a little complicated with dat.json. Maybe let's start simple and say that `dat.json` is only generated on `dat create`. `dat.meta` is a feature for JS users that doesn't really have to be there right now -- if someone wants to read the dat.json we can provide a function to do that later on. This will help us parse out what is actually needed for this 1.0 release so we can focus on the necessary functionality (and release sooner) What do you think?
