### ISSUE TITLE
network.peers

### ISSUE THREAD

**Issue by karissa** [datproject/dat-node#58]
In the network file we have a `.peers()` function: https://github.com/datproject/dat-node/blob/1.0/lib/network.js

that mimics the `.connected` function that already exists on the `swarm` object. It probably should just keep the same name (`.connected()`) to reduce confusion across modules

**Comment by joehand** [comment]
Oh cool! Had no idea discovery swarm exposed that (and as a getter too).

**Comment by joehand** [comment]
Changed in https://github.com/datproject/dat-node/commit/9e0e9683852fa6ae80401db8efe14d6daa01f475
