### ISSUE TITLE
save port option to database

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#59]
Port should be saved to database so we don't try with different ports.

**Comment by joehand** [comment]
Not sure how to do this. All our networking APIs are sync. But we'd need to lookup the old port async. Issue in hyperdiscovery: https://github.com/karissa/hyperdiscovery/issues/1

We could make `dat.joinNetwork(opts, cb)` async but seems less than ideal.

**Comment by karissa** [comment]
Is there an event you can listen for on the swarm?

**Comment by joehand** [comment]
> Is there an event you can listen for on the swarm?

Yep, that is one part of it! `swarm.once('listening', savePortToDB)`. This is async but doesn't really matter since we won't need the port until next time this is run.

The other part is reading the port from the db. This needs to happen before hyperdiscovery joins the swarm. Copying code from https://github.com/karissa/hyperdiscovery/issues/1:

```js
// Check for existing port saved
// PROBLEM: Happens async
if (opts.port && db) {
    var subDb = sub(db, `${encoding.toStr(archive.discoveryKey)}-network`)
    subDb.get('port', function (err, val) {
      if (err && !err.notFound) throw new Error(err)
      if (val) opts.port = val
      doListen()
    })
}

// Happens sync
opts.autoListen = false
var swarm = hyperdiscovery(archive, opts)
```

So we could make the whole thing async:

```js
if (opts.port && db) {
    var subDb = sub(db, `${encoding.toStr(archive.discoveryKey)}-network`)
    subDb.get('port', function (err, val) {
      if (err && !err.notFound) throw new Error(err)
      if (val) opts.port = val
      
      var swarm = hyperdiscovery(archive, opts)
      cb(null, swarm)
    })
}
```

**Comment by joehand** [comment]
Feels like its pretty complex and minor bug. Going to move to next milestone so I can release 1.2 =)

**Comment by joehand** [comment]
We will be mostly removing our leveldb dependency with SLEEP, so I am not going to add this for now. We can revisit after sleep. Might be able to move to toiletdb and save as `.dat/config.json` or something.

**Comment by joehand** [comment]
I guess we could make local and global config things like npm/git do. This should be a CLI thing though, not dat-node. Closing this one.
