### ISSUE TITLE
release as dat-node 1.0

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#61]
I'm happy with the API as it is, enough to release as dat-node 1.0, once all the other issues in https://github.com/datproject/dat-node/milestone/1 are finished.

Okay?

**Comment by karissa** [comment]
Yes!

**Comment by karissa** [comment]
Yes!

**Comment by juliangruber** [comment]
+1

**Comment by joehand** [comment]
Released as 1.0.0 🎉  🎈
