### ISSUE TITLE
set imports opts.indexing true

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#64]
If src = dest indexing should be true on import: https://github.com/datproject/dat-node/tree/add-indexing

**Comment by karissa** [comment]
Should this be default on in hyperdrive importer?

**Comment by joehand** [comment]
> Should this be default on in hyperdrive importer?

We only want this if we know the target and the source are the same. I think it'd break if we had that as default and that wasn't true. 

hyperdrive-import takes `(archive, target)`. It'd be cool if we could check if `archive.dir === target` but I don't think thats part of the hyperdrive API.

**Comment by joehand** [comment]
[Added](https://github.com/datproject/dat-node/blob/master/dat.js#L92) with multdrive PR merge.
