### ISSUE TITLE
files not updating properly

### ISSUE THREAD

**Issue by aaronshaf** [datproject/dat-node#79]
I am using `dat sync` (of dat-next) on one computer, and dat-node's `dat.joinNetwork({})` in another. I made a simple `index.html` with "Hello world." On the origin computer I replaced the text with some text, "12345", etc.

On the second computer: Instead of replacing "Hello world" with "12345", it appends the file with new lines of partial text.

**Comment by joehand** [comment]
Yes! Not a fun 🐛 . 

Right now Dat does not handle deletion of bytes from a files (or files at all). Your hello world file may be 20B. The extra text is the difference between that and the shorter 12345 file.

We need to prioritize this bug. Another issue with the same bug: https://github.com/datproject/dat/issues/517 and related PR: https://github.com/mafintosh/hyperdrive/pull/99.

Thanks for filing the issue!

**Comment by aaronshaf** [comment]
@joehand Can you recommend a temporary workaround?

**Comment by joehand** [comment]
If the file stays the same length, you shouldn't see the bug. So you can pad it with blank bytes or a comment:

Before: 

```html
<h1>hello world</h1>
```

After: 

```html
<h1>short         </h1>   <!-- extra spaces to be the same length or a comment -->
```

**Comment by aaronshaf** [comment]
I am looking for a workaround at the level of dat-node. I am helping others use dat. I can't modify their actual data :-(

**Comment by maxogden** [comment]
@aaronshaf hey sorry you hit this bug, i'm looking into it with @joehand and will get back to you soon here

**Comment by karissa** [comment]
Thanks for reporting this @aaronshaf , let us know if that fixes your issue after you update to the latest version of dat-node!

**Comment by aaronshaf** [comment]
❤️ ❤️ ❤️ !
