### ISSUE TITLE
.close stalls when replicating

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-node#84]
When you call `dat.close(cb)` while it's still replicating data, it will never call the close callback

**Comment by joehand** [comment]
Hmm I saw this too but thought I fixed it closing the network/importer before the archive.

We can probably call `archive.unreplicate` as the first thing in close.

**Comment by juliangruber** [comment]
I'm not 100% at this point if this is a dat-* bug or was caused by some UI issue in dat-desktop not triggering some action. So take this "bug report" with a grain of salt. I'll report back here if I can reproduce after the UI issue has been addressed.

**Comment by joehand** [comment]
published in `1.3.2`
