### ISSUE TITLE
dat.close not closing database (seg faults often)

### ISSUE THREAD

**Issue by joehand** [datproject/dat-node#98]
Something in a recent hyperdrive/hypercore update (I think) made it so we are getting segfaults on `db.close()` a lot and close isn't calling back. I noticed this first in PR #95 but have not been able to diagnose it (or fix it). 

I tried taking out `db.close()` and doing it manually later but it still wasn't closing.

**Comment by joehand** [comment]
It happened in this commit/release for hyperdrive https://github.com/mafintosh/hyperdrive/commit/eb0b9fe150fcbd5c595e342eb55855fb4987dc4b

**Comment by juliangruber** [comment]
In my understanding different changes like the one above just make it more or less likely for the segfault to appear, but none are fixing the real issue, which most likely lies in leveldown still.

Fortunately we're switching to SLEEP :) Until then though, do we even have the resources to debug leveldown code? Or would something like using dat-worker in the cli and other projects be a good intermediate solution.

**Comment by joehand** [comment]
I don't think it should segfault anymore because we don't use leveldb.
